### ISSUE TITLE
Where c# code is getting generated 

### ISSUE THREAD

**Issue by gnaneswarreddy** [gian-te/ui-automation-recorder-playback#1]
I am not able to see where c# code is getting generated , able to record actions how to generate code

**Comment by gian-te** [comment]
> you’re supposed to traverse the list of actions and check the action type, then export it to C# code by yourself. For every action do a driver.findelement by xpath based on the properties retrieved. This is easy enough to do if you’ve done any UI automation before

**Comment by gian-te** [comment]
Do that in the WpfApp’s window’s code behind, where you add a button and that loops through the list of Steps. For every action change the corresponding method that you’ll call (e.g. if it’s a click, do a driver.findelement() and then do an element.click()) then simply save the code generated as a .cs file which you can create as a runnable unit test in MSTest. I have this code ready but I can’t share that part in this public repo because it contains proprietary information relating to xpath generation.

Also, this part of exporting to C# code will differ for every developer and team performing the automation, so there is no one-size-fits-all code that will work for everyone
